# Generated by Django 5.2.3 on 2026-10-08 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_area', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('rut_empresa', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='ObservacionTerreno',
            fields=[
                ('id_observacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('hora_registro', models.TimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('ubicacion_observacion', models.JSONField()),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
            ],
            options={
                'db_table': 'observacion_terreno',
            },
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id_fotografia', models.AutoField(primary_key=True, serialize=False)),
                ('url_fotografia', models.CharField(max_length=255)),
                ('id_observacion', models.ForeignKey(db_column='id_observacion', on_delete=django.db.models.deletion.CASCADE, to='tickets.observacionterreno')),
            ],
            options={
                'db_table': 'fotografia',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(max_length=50)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.empresa')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.AddField(
            model_name='observacionterreno',
            name='id_fiscalizador',
            field=models.ForeignKey(db_column='id_fiscalizador', on_delete=django.db.models.deletion.RESTRICT, to='tickets.usuario'),
        ),
    ]
